version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: everest
    volumes:
      - mysql-data:/var/lib/mysql

  celery_worker:
    build: .
    command: celery -A app.celery worker --pool=solo -l info
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  celery_beat:
    build: .
    command: celery -A app.celery beat -l info
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  mysql-data:

